### Create Booking By User
POST http://localhost:6000/bookings/create-booking/08f6bba2-7817-4413-9d1b-8bf9b4e23a9a
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNTQ4YjNhNzItMDg1ZS00YWNhLWJhMWItNWIyNDQ1YjczYzQ5IiwiZnVsbG5hbWUiOiJqb2hhbiBTbWl0aCIsInBob25lX251bWJlciI6IjA3MjIzNDU2NjgiLCJlbWFpbCI6ImpvaGFuMDAxQGdtYWlsLmNvbSIsImNvdW50cnkiOiJLZW55YSIsImFkZHJlc3MiOiI0NTYtMDAxLCBOYWlyb2JpIiwicHJvZmlsZV9pbWFnZSI6ImRhdGE6aW1hZ2UvanBlZztiYXNlNjQsLzlqLzRBQVFTa1pKUmdBQkFRQUFBUUFCQUFELzJ3Q0VBQnNiR3hzY0d4NGhJUjRxTFNndEtqMDRNek00UFYxQ1IwSkhRbDJOV0dkWVdHZFlqWDJYZTNON2wzM2dzSnljc09ELzJjN1ovLy8vLy8vLy8vLy8vLzhCR3hzYkd4d2JIaUVoSGlvdEtDMHFQVGd6TXpnOVhVSkhRa2RDWFkxWVoxaFlaMWlOZlpkN2MzdVhmZUN3bkp5dzRQL1p6dG4vLy8vLy8vLy8vLy8vLy8vQ0FCRUlBU1lBMUFNQklnQUNFUUVERVFILyIsInBhc3N3b3JkIjoiJDJiJDEyJERPSHBqdXhZQVZySXo4M3dYZlRSZXVySzZuSFViRWFEeHR5dkNuMzlvWmhlbXBJMEtzZVBLIiwiY3JlYXRlZEF0IjoiMjAyNC0wNy0xOVQwMDowMDowMC4wMDBaIiwicm9sZSI6ImF0dGVuZGVlIiwiaXNNYW5hZ2VyIjpmYWxzZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lZCI6ZmFsc2UsImlhdCI6MTcyMTM5NTM2MCwiZXhwIjoxNzIxNDAyNTYwfQ.1-AEVzVlPX0qgD30ollks7IZcXMnpogYQgemO3mwSOs

{
  "ticket_type": "groups"
}

### Update Booking By User
PUT http://localhost:6000/bookings/update-booking/c4007b21-5193-47b2-9d2f-3144503081a5
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNTQ4YjNhNzItMDg1ZS00YWNhLWJhMWItNWIyNDQ1YjczYzQ5IiwiZnVsbG5hbWUiOiJqb2hhbiBTbWl0aCIsInBob25lX251bWJlciI6IjA3MjIzNDU2NjgiLCJlbWFpbCI6ImpvaGFuMDAxQGdtYWlsLmNvbSIsImNvdW50cnkiOiJLZW55YSIsImFkZHJlc3MiOiI0NTYtMDAxLCBOYWlyb2JpIiwicHJvZmlsZV9pbWFnZSI6ImRhdGE6aW1hZ2UvanBlZztiYXNlNjQsLzlqLzRBQVFTa1pKUmdBQkFRQUFBUUFCQUFELzJ3Q0VBQnNiR3hzY0d4NGhJUjRxTFNndEtqMDRNek00UFYxQ1IwSkhRbDJOV0dkWVdHZFlqWDJYZTNON2wzM2dzSnljc09ELzJjN1ovLy8vLy8vLy8vLy8vLzhCR3hzYkd4d2JIaUVoSGlvdEtDMHFQVGd6TXpnOVhVSkhRa2RDWFkxWVoxaFlaMWlOZlpkN2MzdVhmZUN3bkp5dzRQL1p6dG4vLy8vLy8vLy8vLy8vLy8vQ0FCRUlBU1lBMUFNQklnQUNFUUVERVFILyIsInBhc3N3b3JkIjoiJDJiJDEyJERPSHBqdXhZQVZySXo4M3dYZlRSZXVySzZuSFViRWFEeHR5dkNuMzlvWmhlbXBJMEtzZVBLIiwiY3JlYXRlZEF0IjoiMjAyNC0wNy0xOVQwMDowMDowMC4wMDBaIiwicm9sZSI6ImF0dGVuZGVlIiwiaXNNYW5hZ2VyIjpmYWxzZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lZCI6ZmFsc2UsImlhdCI6MTcyMTM5NTM2MCwiZXhwIjoxNzIxNDAyNTYwfQ.1-AEVzVlPX0qgD30ollks7IZcXMnpogYQgemO3mwSOs

{
  "ticket_type": "singles"
}

### Delete Booking By User
DELETE http://localhost:6000/bookings/delete-booking/0ac41ce6-1140-4520-9c1b-e2b54c0f6f43
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzkzZDE4MmEtMGQyMC00MTQyLWJiMTQtOWQ4OWEyNjUwNjIzIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCBPd3VvciIsInBob25lX251bWJlciI6IjA3NjgwMzA0NzgiLCJlbWFpbCI6ImZlbGl4b2tvdGgwNzhAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjkxMC0zMDEwMCwgVWFzaW4gR2lzaHUiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAudzZuYThmR0luZ0RQa0NiX0d6RWxid0FBQUEmdz0yOTAmaD0yMTUmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiR1bDNyUnhsSEFBZC42aXJwMkxGN2xPU3lSVjIwNEYzL2pRckc5Mzc0bGJLWFIzZXcxYzlzQyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJhZG1pbiIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MjExOTYzMjgsImV4cCI6MTcyMTIwMzUyOH0.-0xYTFxJB24tq44PXRZP9O7VxUM9vtQbhyYpl1Nij4U

### Get attendee booking history
GET http://localhost:6000/bookings/get-attendee-booking-history
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzkzZDE4MmEtMGQyMC00MTQyLWJiMTQtOWQ4OWEyNjUwNjIzIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCBPd3VvciIsInBob25lX251bWJlciI6IjA3NjgwMzA0NzgiLCJlbWFpbCI6ImZlbGl4b2tvdGgwNzhAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjkxMC0zMDEwMCwgVWFzaW4gR2lzaHUiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAudzZuYThmR0luZ0RQa0NiX0d6RWxid0FBQUEmdz0yOTAmaD0yMTUmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiR1bDNyUnhsSEFBZC42aXJwMkxGN2xPU3lSVjIwNEYzL2pRckc5Mzc0bGJLWFIzZXcxYzlzQyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJhZG1pbiIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MjEyMDM3NjgsImV4cCI6MTcyMTIxMDk2OH0.GBln1IBwdz7L3kE0EJYf2dbzVb65yWfJOom4migxLf4

### Get event users booking history
GET http://localhost:6000/bookings/get-managers-booked-events-users
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYzUzNTZiMzUtNTE2NC00NTYyLTg3MjQtNmEyMzJlZDg5MWFhIiwiZnVsbG5hbWUiOiJKZWZmIFNtaXRoIiwicGhvbmVfbnVtYmVyIjoiMDcxMjM0NTY2OCIsImVtYWlsIjoiamVmZnNtaXRoMDAxQGdtYWlsLmNvbSIsImNvdW50cnkiOiJLZW55YSIsImFkZHJlc3MiOiI0NTYtMDAxLCBOYWlyb2JpIiwicHJvZmlsZV9pbWFnZSI6ImRhdGE6aW1hZ2UvanBlZztiYXNlNjQsLzlqLzRBQVFTa1pKUmdBQkFRQUFBUUFCQUFELzJ3Q0VBQnNiR3hzY0d4NGhJUjRxTFNndEtqMDRNek00UFYxQ1IwSkhRbDJOV0dkWVdHZFlqWDJYZTNON2wzM2dzSnljc09ELzJjN1ovLy8vLy8vLy8vLy8vLzhCR3hzYkd4d2JIaUVoSGlvdEtDMHFQVGd6TXpnOVhVSkhRa2RDWFkxWVoxaFlaMWlOZlpkN2MzdVhmZUN3bkp5dzRQL1p6dG4vLy8vLy8vLy8vLy8vLy8vQ0FCRUlBU1lBMUFNQklnQUNFUUVERVFILyIsInBhc3N3b3JkIjoiJDJiJDEyJGlBZVJDOHJhZWxWLk5CY29sQTVrV2VraFBwaWowNWhaS0JxOUlRaFgvempVZUFoRjA4bGltIiwiY3JlYXRlZEF0IjoiMjAyNC0wNy0xOVQwMDowMDowMC4wMDBaIiwicm9sZSI6Im1hbmFnZXIiLCJpc01hbmFnZXIiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzIxMzc2NjU5LCJleHAiOjE3MjEzODM4NTl9.TI3VXw__UM835Q-H8mVXDJuvrccb9RJkX26UAG1Gw_o

### Get all bookings
GET http://localhost:6000/bookings/get-all-bookings
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNTQ4YjNhNzItMDg1ZS00YWNhLWJhMWItNWIyNDQ1YjczYzQ5IiwiZnVsbG5hbWUiOiJqb2hhbiBTbWl0aCIsInBob25lX251bWJlciI6IjA3MjIzNDU2NjgiLCJlbWFpbCI6ImpvaGFuMDAxQGdtYWlsLmNvbSIsImNvdW50cnkiOiJLZW55YSIsImFkZHJlc3MiOiI0NTYtMDAxLCBOYWlyb2JpIiwicHJvZmlsZV9pbWFnZSI6ImRhdGE6aW1hZ2UvanBlZztiYXNlNjQsLzlqLzRBQVFTa1pKUmdBQkFRQUFBUUFCQUFELzJ3Q0VBQnNiR3hzY0d4NGhJUjRxTFNndEtqMDRNek00UFYxQ1IwSkhRbDJOV0dkWVdHZFlqWDJYZTNON2wzM2dzSnljc09ELzJjN1ovLy8vLy8vLy8vLy8vLzhCR3hzYkd4d2JIaUVoSGlvdEtDMHFQVGd6TXpnOVhVSkhRa2RDWFkxWVoxaFlaMWlOZlpkN2MzdVhmZUN3bkp5dzRQL1p6dG4vLy8vLy8vLy8vLy8vLy8vQ0FCRUlBU1lBMUFNQklnQUNFUUVERVFILyIsInBhc3N3b3JkIjoiJDJiJDEyJERPSHBqdXhZQVZySXo4M3dYZlRSZXVySzZuSFViRWFEeHR5dkNuMzlvWmhlbXBJMEtzZVBLIiwiY3JlYXRlZEF0IjoiMjAyNC0wNy0xOVQwMDowMDowMC4wMDBaIiwicm9sZSI6ImF0dGVuZGVlIiwiaXNNYW5hZ2VyIjpmYWxzZSwiaXNEZWxldGVkIjpmYWxzZSwiaXNXZWxjb21lZCI6ZmFsc2UsImlhdCI6MTcyMTM5NTM2MCwiZXhwIjoxNzIxNDAyNTYwfQ.1-AEVzVlPX0qgD30ollks7IZcXMnpogYQgemO3mwSOs
