### Create Booking By User
POST http://localhost:6000/bookings/create-booking/924b131c-263e-4bb4-af24-a679d1753c4d
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzkzZDE4MmEtMGQyMC00MTQyLWJiMTQtOWQ4OWEyNjUwNjIzIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCBPd3VvciIsInBob25lX251bWJlciI6IjA3NjgwMzA0NzgiLCJlbWFpbCI6ImZlbGl4b2tvdGgwNzhAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjkxMC0zMDEwMCwgVWFzaW4gR2lzaHUiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAudzZuYThmR0luZ0RQa0NiX0d6RWxid0FBQUEmdz0yOTAmaD0yMTUmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiR1bDNyUnhsSEFBZC42aXJwMkxGN2xPU3lSVjIwNEYzL2pRckc5Mzc0bGJLWFIzZXcxYzlzQyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJhZG1pbiIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MjExODgyNjYsImV4cCI6MTcyMTE5NTQ2Nn0.cOcpGdI6yLVkyCCNniA2hDxO-5AAy1NvqYAHYqaPQW4

{
  "ticket_type": "couple"
}

### Update Booking By User
PUT http://localhost:6000/bookings/update-booking/924b131c-263e-4bb4-af24-a679d1753c4d
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzkzZDE4MmEtMGQyMC00MTQyLWJiMTQtOWQ4OWEyNjUwNjIzIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCBPd3VvciIsInBob25lX251bWJlciI6IjA3NjgwMzA0NzgiLCJlbWFpbCI6ImZlbGl4b2tvdGgwNzhAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjkxMC0zMDEwMCwgVWFzaW4gR2lzaHUiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAudzZuYThmR0luZ0RQa0NiX0d6RWxid0FBQUEmdz0yOTAmaD0yMTUmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiR1bDNyUnhsSEFBZC42aXJwMkxGN2xPU3lSVjIwNEYzL2pRckc5Mzc0bGJLWFIzZXcxYzlzQyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJhZG1pbiIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MjExOTYzMjgsImV4cCI6MTcyMTIwMzUyOH0.-0xYTFxJB24tq44PXRZP9O7VxUM9vtQbhyYpl1Nij4U

{
  "ticket_type": "singles"
}