### Create Booking By User
POST http://localhost:6000/bookings/create-booking/924b131c-263e-4bb4-af24-a679d1753c4d
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzkzZDE4MmEtMGQyMC00MTQyLWJiMTQtOWQ4OWEyNjUwNjIzIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCBPd3VvciIsInBob25lX251bWJlciI6IjA3NjgwMzA0NzgiLCJlbWFpbCI6ImZlbGl4b2tvdGgwNzhAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjkxMC0zMDEwMCwgVWFzaW4gR2lzaHUiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAudzZuYThmR0luZ0RQa0NiX0d6RWxid0FBQUEmdz0yOTAmaD0yMTUmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiR1bDNyUnhsSEFBZC42aXJwMkxGN2xPU3lSVjIwNEYzL2pRckc5Mzc0bGJLWFIzZXcxYzlzQyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJhZG1pbiIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MjEyMDM3NjgsImV4cCI6MTcyMTIxMDk2OH0.GBln1IBwdz7L3kE0EJYf2dbzVb65yWfJOom4migxLf4

{
  "ticket_type": "couple"
}

### Update Booking By User
PUT http://localhost:6000/bookings/update-booking/924b131c-263e-4bb4-af24-a679d1753c4d
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzkzZDE4MmEtMGQyMC00MTQyLWJiMTQtOWQ4OWEyNjUwNjIzIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCBPd3VvciIsInBob25lX251bWJlciI6IjA3NjgwMzA0NzgiLCJlbWFpbCI6ImZlbGl4b2tvdGgwNzhAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjkxMC0zMDEwMCwgVWFzaW4gR2lzaHUiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAudzZuYThmR0luZ0RQa0NiX0d6RWxid0FBQUEmdz0yOTAmaD0yMTUmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiR1bDNyUnhsSEFBZC42aXJwMkxGN2xPU3lSVjIwNEYzL2pRckc5Mzc0bGJLWFIzZXcxYzlzQyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJhZG1pbiIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MjExOTYzMjgsImV4cCI6MTcyMTIwMzUyOH0.-0xYTFxJB24tq44PXRZP9O7VxUM9vtQbhyYpl1Nij4U

{
  "ticket_type": "singles"
}

### Delete Booking By User
DELETE http://localhost:6000/bookings/delete-booking/0ac41ce6-1140-4520-9c1b-e2b54c0f6f43
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzkzZDE4MmEtMGQyMC00MTQyLWJiMTQtOWQ4OWEyNjUwNjIzIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCBPd3VvciIsInBob25lX251bWJlciI6IjA3NjgwMzA0NzgiLCJlbWFpbCI6ImZlbGl4b2tvdGgwNzhAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjkxMC0zMDEwMCwgVWFzaW4gR2lzaHUiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAudzZuYThmR0luZ0RQa0NiX0d6RWxid0FBQUEmdz0yOTAmaD0yMTUmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiR1bDNyUnhsSEFBZC42aXJwMkxGN2xPU3lSVjIwNEYzL2pRckc5Mzc0bGJLWFIzZXcxYzlzQyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJhZG1pbiIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MjExOTYzMjgsImV4cCI6MTcyMTIwMzUyOH0.-0xYTFxJB24tq44PXRZP9O7VxUM9vtQbhyYpl1Nij4U

### Get attendee booking history
GET http://localhost:6000/bookings/get-attendee-booking-history
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzkzZDE4MmEtMGQyMC00MTQyLWJiMTQtOWQ4OWEyNjUwNjIzIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCBPd3VvciIsInBob25lX251bWJlciI6IjA3NjgwMzA0NzgiLCJlbWFpbCI6ImZlbGl4b2tvdGgwNzhAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjkxMC0zMDEwMCwgVWFzaW4gR2lzaHUiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAudzZuYThmR0luZ0RQa0NiX0d6RWxid0FBQUEmdz0yOTAmaD0yMTUmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiR1bDNyUnhsSEFBZC42aXJwMkxGN2xPU3lSVjIwNEYzL2pRckc5Mzc0bGJLWFIzZXcxYzlzQyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJhZG1pbiIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MjEyMDM3NjgsImV4cCI6MTcyMTIxMDk2OH0.GBln1IBwdz7L3kE0EJYf2dbzVb65yWfJOom4migxLf4

### Get event users booking history
GET http://localhost:6000/bookings/get-managers-booked-events-users
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzlhMDdkMmItOGU4MS00MGJmLWJmZTMtN2JmYWQ3YmM5NzBiIiwiZnVsbG5hbWUiOiJCb2IgQmVsY2hlciIsInBob25lX251bWJlciI6IjA3MTIzNDU2NzgiLCJlbWFpbCI6ImJvYmJlbGNoZXIwMDFAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjQ1Ni0wMDEsIE5haXJvYmkiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAuMGFkaXRwQms1NG8wZGlEa3JSMXlpUUhhSmEmdz0yMjEmaD0yODEmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiRQZXVvLlZ5b2p4WHJQdkZkTG5USWF1WERwaHc5ZWVaM3lGVDdib0xwWHdDMkNoUXNXUXpJcSIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJtYW5hZ2VyIiwiaXNNYW5hZ2VyIjp0cnVlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzIxMjA0OTMyLCJleHAiOjE3MjEyMTIxMzJ9.Da8u4RosqIPkZwovXyfA3Aw2LpsQxxlcdHj8ZqxItXc
