### create event by manager
POST http://localhost:6000/events/create-event
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzlhMDdkMmItOGU4MS00MGJmLWJmZTMtN2JmYWQ3YmM5NzBiIiwiZnVsbG5hbWUiOiJCb2IgQmVsY2hlciIsInBob25lX251bWJlciI6IjA3MTIzNDU2NzgiLCJlbWFpbCI6ImJvYmJlbGNoZXIwMDFAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjQ1Ni0wMDEsIE5haXJvYmkiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAuMGFkaXRwQms1NG8wZGlEa3JSMXlpUUhhSmEmdz0yMjEmaD0yODEmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiRQZXVvLlZ5b2p4WHJQdkZkTG5USWF1WERwaHc5ZWVaM3lGVDdib0xwWHdDMkNoUXNXUXpJcSIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJtYW5hZ2VyIiwiaXNNYW5hZ2VyIjp0cnVlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzIxMTgwMzAwLCJleHAiOjE3MjExODc1MDB9.88x7eCazqRFAkOW1vmG1SEUWURnnvHiP-AsCl0fEZWE

{
  "event_name": "Music Alation Concert",
  "short_desc": "Music concerts for teenagers and adults",
  "long_desc": "Cara Logman along side J.Simons will be joining us for a sing off hosting th event at around noon.",
  "location": "Jumbo Valley - 910",
  "start_date": "2024-07-20",
  "end_date": "2024-07-20",
  "images": "[image1, image2]",
  "singles": "0",
  "couple": "2500",
  "groups": "0",
  "no_of_tickets": "16",
  "booking_deadline": "2024-07-19"
}

### update event by manager
PUT http://localhost:6000/events/update-event/924b131c-263e-4bb4-af24-a679d1753c4d
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzlhMDdkMmItOGU4MS00MGJmLWJmZTMtN2JmYWQ3YmM5NzBiIiwiZnVsbG5hbWUiOiJCb2IgQmVsY2hlciIsInBob25lX251bWJlciI6IjA3MTIzNDU2NzgiLCJlbWFpbCI6ImJvYmJlbGNoZXIwMDFAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjQ1Ni0wMDEsIE5haXJvYmkiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAuMGFkaXRwQms1NG8wZGlEa3JSMXlpUUhhSmEmdz0yMjEmaD0yODEmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiRQZXVvLlZ5b2p4WHJQdkZkTG5USWF1WERwaHc5ZWVaM3lGVDdib0xwWHdDMkNoUXNXUXpJcSIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJtYW5hZ2VyIiwiaXNNYW5hZ2VyIjp0cnVlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzIxMTgwMzAwLCJleHAiOjE3MjExODc1MDB9.88x7eCazqRFAkOW1vmG1SEUWURnnvHiP-AsCl0fEZWE

{
  "event_name": "Double Date Dinners Night Out",
  "short_desc": "Couple's night out, fun and enjoyment",
  "long_desc": "Couples night, a dinner hosting our night out. Best of services  offered and one of the best meals of all. At Oak Road Motel",
  "location": "Oak Road - 9010",
  "start_date": "2024-07-20",
  "end_date": "2024-07-20",
  "images": "[image1, image2]",
  "singles": "0",
  "couple": "2500",
  "groups": "0",
  "no_of_tickets": "16",
  "booking_deadline": "2024-07-19"
}

### get all events
GET http://localhost:6000/events/get-all-events
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzkzZDE4MmEtMGQyMC00MTQyLWJiMTQtOWQ4OWEyNjUwNjIzIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCBPd3VvciIsInBob25lX251bWJlciI6IjA3NjgwMzA0NzgiLCJlbWFpbCI6ImZlbGl4b2tvdGgwNzhAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjkxMC0zMDEwMCwgVWFzaW4gR2lzaHUiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAudzZuYThmR0luZ0RQa0NiX0d6RWxid0FBQUEmdz0yOTAmaD0yMTUmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiR1bDNyUnhsSEFBZC42aXJwMkxGN2xPU3lSVjIwNEYzL2pRckc5Mzc0bGJLWFIzZXcxYzlzQyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJhZG1pbiIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MjEyMDM3NjgsImV4cCI6MTcyMTIxMDk2OH0.GBln1IBwdz7L3kE0EJYf2dbzVb65yWfJOom4migxLf4

### Update event status
PUT http://localhost:6000/events/update-event-status/924b131c-263e-4bb4-af24-a679d1753c4d
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzlhMDdkMmItOGU4MS00MGJmLWJmZTMtN2JmYWQ3YmM5NzBiIiwiZnVsbG5hbWUiOiJCb2IgQmVsY2hlciIsInBob25lX251bWJlciI6IjA3MTIzNDU2NzgiLCJlbWFpbCI6ImJvYmJlbGNoZXIwMDFAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjQ1Ni0wMDEsIE5haXJvYmkiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAuMGFkaXRwQms1NG8wZGlEa3JSMXlpUUhhSmEmdz0yMjEmaD0yODEmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiRQZXVvLlZ5b2p4WHJQdkZkTG5USWF1WERwaHc5ZWVaM3lGVDdib0xwWHdDMkNoUXNXUXpJcSIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJtYW5hZ2VyIiwiaXNNYW5hZ2VyIjp0cnVlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzIxMTgwMzAwLCJleHAiOjE3MjExODc1MDB9.88x7eCazqRFAkOW1vmG1SEUWURnnvHiP-AsCl0fEZWE

### Update all event status
PUT http://localhost:6000/events/update-all-event-status
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzlhMDdkMmItOGU4MS00MGJmLWJmZTMtN2JmYWQ3YmM5NzBiIiwiZnVsbG5hbWUiOiJCb2IgQmVsY2hlciIsInBob25lX251bWJlciI6IjA3MTIzNDU2NzgiLCJlbWFpbCI6ImJvYmJlbGNoZXIwMDFAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjQ1Ni0wMDEsIE5haXJvYmkiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAuMGFkaXRwQms1NG8wZGlEa3JSMXlpUUhhSmEmdz0yMjEmaD0yODEmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiRQZXVvLlZ5b2p4WHJQdkZkTG5USWF1WERwaHc5ZWVaM3lGVDdib0xwWHdDMkNoUXNXUXpJcSIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJtYW5hZ2VyIiwiaXNNYW5hZ2VyIjp0cnVlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzIxMTgwMzAwLCJleHAiOjE3MjExODc1MDB9.88x7eCazqRFAkOW1vmG1SEUWURnnvHiP-AsCl0fEZWE

### Get events by event id
GET http://localhost:6000/events/get-event-by-id/924b131c-263e-4bb4-af24-a679d1753c4d
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzlhMDdkMmItOGU4MS00MGJmLWJmZTMtN2JmYWQ3YmM5NzBiIiwiZnVsbG5hbWUiOiJCb2IgQmVsY2hlciIsInBob25lX251bWJlciI6IjA3MTIzNDU2NzgiLCJlbWFpbCI6ImJvYmJlbGNoZXIwMDFAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjQ1Ni0wMDEsIE5haXJvYmkiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAuMGFkaXRwQms1NG8wZGlEa3JSMXlpUUhhSmEmdz0yMjEmaD0yODEmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiRQZXVvLlZ5b2p4WHJQdkZkTG5USWF1WERwaHc5ZWVaM3lGVDdib0xwWHdDMkNoUXNXUXpJcSIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJtYW5hZ2VyIiwiaXNNYW5hZ2VyIjp0cnVlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzIxMTgwMzAwLCJleHAiOjE3MjExODc1MDB9.88x7eCazqRFAkOW1vmG1SEUWURnnvHiP-AsCl0fEZWE

### Get events by date created
GET http://localhost:6000/events/get-events-by-date-created
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzlhMDdkMmItOGU4MS00MGJmLWJmZTMtN2JmYWQ3YmM5NzBiIiwiZnVsbG5hbWUiOiJCb2IgQmVsY2hlciIsInBob25lX251bWJlciI6IjA3MTIzNDU2NzgiLCJlbWFpbCI6ImJvYmJlbGNoZXIwMDFAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjQ1Ni0wMDEsIE5haXJvYmkiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAuMGFkaXRwQms1NG8wZGlEa3JSMXlpUUhhSmEmdz0yMjEmaD0yODEmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiRQZXVvLlZ5b2p4WHJQdkZkTG5USWF1WERwaHc5ZWVaM3lGVDdib0xwWHdDMkNoUXNXUXpJcSIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJtYW5hZ2VyIiwiaXNNYW5hZ2VyIjp0cnVlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzIxMTgwMzAwLCJleHAiOjE3MjExODc1MDB9.88x7eCazqRFAkOW1vmG1SEUWURnnvHiP-AsCl0fEZWE

### Delete event
DELETE http://localhost:6000/events/delete-event/f0898169-bd03-40a9-8059-2ab8ce517839
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzlhMDdkMmItOGU4MS00MGJmLWJmZTMtN2JmYWQ3YmM5NzBiIiwiZnVsbG5hbWUiOiJCb2IgQmVsY2hlciIsInBob25lX251bWJlciI6IjA3MTIzNDU2NzgiLCJlbWFpbCI6ImJvYmJlbGNoZXIwMDFAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjQ1Ni0wMDEsIE5haXJvYmkiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAuMGFkaXRwQms1NG8wZGlEa3JSMXlpUUhhSmEmdz0yMjEmaD0yODEmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiRQZXVvLlZ5b2p4WHJQdkZkTG5USWF1WERwaHc5ZWVaM3lGVDdib0xwWHdDMkNoUXNXUXpJcSIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJtYW5hZ2VyIiwiaXNNYW5hZ2VyIjp0cnVlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzIxMTgwMzAwLCJleHAiOjE3MjExODc1MDB9.88x7eCazqRFAkOW1vmG1SEUWURnnvHiP-AsCl0fEZWE
