### create event by manager
POST http://localhost:3000/events/create-event
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNTQ4YjNhNzItMDg1ZS00YWNhLWJhMWItNWIyNDQ1YjczYzQ5IiwiZnVsbG5hbWUiOiJqb2hhbiBTbWl0aCIsInBob25lX251bWJlciI6IjA3MjIzNDU2NjgiLCJlbWFpbCI6ImpvaGFuMDAxQGdtYWlsLmNvbSIsImNvdW50cnkiOiJLZW55YSIsImFkZHJlc3MiOiI0NTYtMDAxLCBOYWlyb2JpIiwicHJvZmlsZV9pbWFnZSI6ImRhdGE6aW1hZ2UvanBlZztiYXNlNjQsLzlqLzRBQVFTa1pKUmdBQkFRQUFBUUFCQUFELzJ3Q0VBQnNiR3hzY0d4NGhJUjRxTFNndEtqMDRNek00UFYxQ1IwSkhRbDJOV0dkWVdHZFlqWDJYZTNON2wzM2dzSnljc09ELzJjN1ovLy8vLy8vLy8vLy8vLzhCR3hzYkd4d2JIaUVoSGlvdEtDMHFQVGd6TXpnOVhVSkhRa2RDWFkxWVoxaFlaMWlOZlpkN2MzdVhmZUN3bkp5dzRQL1p6dG4vLy8vLy8vLy8vLy8vLy8vQ0FCRUlBU1lBMUFNQklnQUNFUUVERVFILyIsInBhc3N3b3JkIjoiJDJiJDEyJERPSHBqdXhZQVZySXo4M3dYZlRSZXVySzZuSFViRWFEeHR5dkNuMzlvWmhlbXBJMEtzZVBLIiwiY3JlYXRlZEF0IjoiMjAyNC0wNy0xOVQwMDowMDowMC4wMDBaIiwicm9sZSI6ImF0dGVuZGVlIiwiaXNNYW5hZ2VyIjp0cnVlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzIxMzk1Njc2LCJleHAiOjE3MjE0MDI4NzZ9.qkzE75UelLgWSD89lSbNn1J2p-a6EtX1UDkeNX9bXhQ

{
  "event_name": "Testing",
  "short_desc": "Music concerts for teenagers and adults",
  "long_desc": "Cara Logman along side J.Simons will be joining us for a sing off hosting th event at around noon.",
  "location": "Jumbo Valley - 910",
  "start_date": "2024-07-20",
  "end_date": "2024-07-20",
  "images": "[image1, image2]",
  "singles": 1000,
  "couple": 2500,
  "groups": 900,
  "no_of_tickets": "16",
  "booking_deadline": "2024-07-19"
}

### update event by manager
PUT http://localhost:3000/events/update-event/924b131c-263e-4bb4-af24-a679d1753c4d
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzlhMDdkMmItOGU4MS00MGJmLWJmZTMtN2JmYWQ3YmM5NzBiIiwiZnVsbG5hbWUiOiJCb2IgQmVsY2hlciIsInBob25lX251bWJlciI6IjA3MTIzNDU2NzgiLCJlbWFpbCI6ImJvYmJlbGNoZXIwMDFAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjQ1Ni0wMDEsIE5haXJvYmkiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAuMGFkaXRwQms1NG8wZGlEa3JSMXlpUUhhSmEmdz0yMjEmaD0yODEmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiRQZXVvLlZ5b2p4WHJQdkZkTG5USWF1WERwaHc5ZWVaM3lGVDdib0xwWHdDMkNoUXNXUXpJcSIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJtYW5hZ2VyIiwiaXNNYW5hZ2VyIjp0cnVlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzIxMTgwMzAwLCJleHAiOjE3MjExODc1MDB9.88x7eCazqRFAkOW1vmG1SEUWURnnvHiP-AsCl0fEZWE

{
  "event_name": "Double Date Dinners Night Out",
  "short_desc": "Couple's night out, fun and enjoyment",
  "long_desc": "Couples night, a dinner hosting our night out. Best of services  offered and one of the best meals of all. At Oak Road Motel",
  "location": "Oak Road - 9010",
  "start_date": "2024-07-20",
  "end_date": "2024-07-20",
  "images": "[image1, image2]",
  "singles": "0",
  "couple": "2500",
  "groups": "0",
  "no_of_tickets": "16",
  "booking_deadline": "2024-07-19"
}

### get all events
GET http://localhost:3000/events/get-all-events
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNTQ4YjNhNzItMDg1ZS00YWNhLWJhMWItNWIyNDQ1YjczYzQ5IiwiZnVsbG5hbWUiOiJqb2hhbiBTbWl0aCIsInBob25lX251bWJlciI6IjA3MjIzNDU2NjgiLCJlbWFpbCI6ImpvaGFuMDAxQGdtYWlsLmNvbSIsImNvdW50cnkiOiJLZW55YSIsImFkZHJlc3MiOiI0NTYtMDAxLCBOYWlyb2JpIiwicHJvZmlsZV9pbWFnZSI6ImRhdGE6aW1hZ2UvanBlZztiYXNlNjQsLzlqLzRBQVFTa1pKUmdBQkFRQUFBUUFCQUFELzJ3Q0VBQnNiR3hzY0d4NGhJUjRxTFNndEtqMDRNek00UFYxQ1IwSkhRbDJOV0dkWVdHZFlqWDJYZTNON2wzM2dzSnljc09ELzJjN1ovLy8vLy8vLy8vLy8vLzhCR3hzYkd4d2JIaUVoSGlvdEtDMHFQVGd6TXpnOVhVSkhRa2RDWFkxWVoxaFlaMWlOZlpkN2MzdVhmZUN3bkp5dzRQL1p6dG4vLy8vLy8vLy8vLy8vLy8vQ0FCRUlBU1lBMUFNQklnQUNFUUVERVFILyIsInBhc3N3b3JkIjoiJDJiJDEyJERPSHBqdXhZQVZySXo4M3dYZlRSZXVySzZuSFViRWFEeHR5dkNuMzlvWmhlbXBJMEtzZVBLIiwiY3JlYXRlZEF0IjoiMjAyNC0wNy0xOVQwMDowMDowMC4wMDBaIiwicm9sZSI6ImF0dGVuZGVlIiwiaXNNYW5hZ2VyIjp0cnVlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzIxMzk1Njc2LCJleHAiOjE3MjE0MDI4NzZ9.qkzE75UelLgWSD89lSbNn1J2p-a6EtX1UDkeNX9bXhQ

### Update event status
PUT http://localhost:3000/events/update-event-status/0f1869f0-52f9-4946-94a8-830e1fc69fbb
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzkzZDE4MmEtMGQyMC00MTQyLWJiMTQtOWQ4OWEyNjUwNjIzIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCBPd3VvciIsInBob25lX251bWJlciI6IjA3NjgwMzA0NzgiLCJlbWFpbCI6ImZlbGl4b2tvdGgwNzhAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjkxMC0zMDEwMCwgVWFzaW4gR2lzaHUiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAudzZuYThmR0luZ0RQa0NiX0d6RWxid0FBQUEmdz0yOTAmaD0yMTUmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiR1bDNyUnhsSEFBZC42aXJwMkxGN2xPU3lSVjIwNEYzL2pRckc5Mzc0bGJLWFIzZXcxYzlzQyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJhZG1pbiIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MjEzOTcyMDcsImV4cCI6MTcyMTQwNDQwN30.V5Zb7h-4zeVcWzIg1fUqgVREniZUXNShWTqIgwoWcwE

### Update all event status
PUT http://localhost:3000/events/update-all-event-status
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzlhMDdkMmItOGU4MS00MGJmLWJmZTMtN2JmYWQ3YmM5NzBiIiwiZnVsbG5hbWUiOiJCb2IgQmVsY2hlciIsInBob25lX251bWJlciI6IjA3MTIzNDU2NzgiLCJlbWFpbCI6ImJvYmJlbGNoZXIwMDFAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjQ1Ni0wMDEsIE5haXJvYmkiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAuMGFkaXRwQms1NG8wZGlEa3JSMXlpUUhhSmEmdz0yMjEmaD0yODEmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiRQZXVvLlZ5b2p4WHJQdkZkTG5USWF1WERwaHc5ZWVaM3lGVDdib0xwWHdDMkNoUXNXUXpJcSIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJtYW5hZ2VyIiwiaXNNYW5hZ2VyIjp0cnVlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzIxMTgwMzAwLCJleHAiOjE3MjExODc1MDB9.88x7eCazqRFAkOW1vmG1SEUWURnnvHiP-AsCl0fEZWE

### Get events by event id
GET http://localhost:3000/events/get-event-by-id/924b131c-263e-4bb4-af24-a679d1753c4d
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzlhMDdkMmItOGU4MS00MGJmLWJmZTMtN2JmYWQ3YmM5NzBiIiwiZnVsbG5hbWUiOiJCb2IgQmVsY2hlciIsInBob25lX251bWJlciI6IjA3MTIzNDU2NzgiLCJlbWFpbCI6ImJvYmJlbGNoZXIwMDFAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjQ1Ni0wMDEsIE5haXJvYmkiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAuMGFkaXRwQms1NG8wZGlEa3JSMXlpUUhhSmEmdz0yMjEmaD0yODEmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiRQZXVvLlZ5b2p4WHJQdkZkTG5USWF1WERwaHc5ZWVaM3lGVDdib0xwWHdDMkNoUXNXUXpJcSIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJtYW5hZ2VyIiwiaXNNYW5hZ2VyIjp0cnVlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzIxMTgwMzAwLCJleHAiOjE3MjExODc1MDB9.88x7eCazqRFAkOW1vmG1SEUWURnnvHiP-AsCl0fEZWE

### Get events by manager id
GET http://localhost:3000/events/get-event-by-user-id
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzlhMDdkMmItOGU4MS00MGJmLWJmZTMtN2JmYWQ3YmM5NzBiIiwiZnVsbG5hbWUiOiJCb2IgQmVsY2hlciIsInBob25lX251bWJlciI6IjA3MTIzNDU2NzgiLCJlbWFpbCI6ImJvYmJlbGNoZXIwMDFAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjQ1Ni0wMDEsIE5haXJvYmkiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAuMGFkaXRwQms1NG8wZGlEa3JSMXlpUUhhSmEmdz0yMjEmaD0yODEmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiRQZXVvLlZ5b2p4WHJQdkZkTG5USWF1WERwaHc5ZWVaM3lGVDdib0xwWHdDMkNoUXNXUXpJcSIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJtYW5hZ2VyIiwiaXNNYW5hZ2VyIjp0cnVlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzIxNTc5MjU4LCJleHAiOjE3MjE1ODY0NTh9.IbHfAtTyY21bumsE-M7Q4O1VahqRaClEFOA5hET0bRU

### Get events by date created
GET http://localhost:3000/events/get-events-by-date-created
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzlhMDdkMmItOGU4MS00MGJmLWJmZTMtN2JmYWQ3YmM5NzBiIiwiZnVsbG5hbWUiOiJCb2IgQmVsY2hlciIsInBob25lX251bWJlciI6IjA3MTIzNDU2NzgiLCJlbWFpbCI6ImJvYmJlbGNoZXIwMDFAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjQ1Ni0wMDEsIE5haXJvYmkiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAuMGFkaXRwQms1NG8wZGlEa3JSMXlpUUhhSmEmdz0yMjEmaD0yODEmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiRQZXVvLlZ5b2p4WHJQdkZkTG5USWF1WERwaHc5ZWVaM3lGVDdib0xwWHdDMkNoUXNXUXpJcSIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJtYW5hZ2VyIiwiaXNNYW5hZ2VyIjp0cnVlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzIxMTgwMzAwLCJleHAiOjE3MjExODc1MDB9.88x7eCazqRFAkOW1vmG1SEUWURnnvHiP-AsCl0fEZWE

### Delete event
DELETE http://localhost:3000/events/delete-event/f0898169-bd03-40a9-8059-2ab8ce517839
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzlhMDdkMmItOGU4MS00MGJmLWJmZTMtN2JmYWQ3YmM5NzBiIiwiZnVsbG5hbWUiOiJCb2IgQmVsY2hlciIsInBob25lX251bWJlciI6IjA3MTIzNDU2NzgiLCJlbWFpbCI6ImJvYmJlbGNoZXIwMDFAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjQ1Ni0wMDEsIE5haXJvYmkiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAuMGFkaXRwQms1NG8wZGlEa3JSMXlpUUhhSmEmdz0yMjEmaD0yODEmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiRQZXVvLlZ5b2p4WHJQdkZkTG5USWF1WERwaHc5ZWVaM3lGVDdib0xwWHdDMkNoUXNXUXpJcSIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJtYW5hZ2VyIiwiaXNNYW5hZ2VyIjp0cnVlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzIxMTgwMzAwLCJleHAiOjE3MjExODc1MDB9.88x7eCazqRFAkOW1vmG1SEUWURnnvHiP-AsCl0fEZWE
