### Register User
POST http://localhost:6000/users/register
Content-Type: application/json

{
  "fullname": "Bob Belcher",
  "phone_number": "0712345678",
  "email": "bobbelcher001@gmail.com",
  "country": "Kenya",
  "address": "456-001, Nairobi",
  "profile_image": "https://th.bing.com/th?id=OIP.0aditpBk54o0diDkrR1yiQHaJa&w=221&h=281&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
  "password": "Pass@123",
  "role": "manager"
}

### Modify/update User
POST http://localhost:6000/users/update
Content-type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzkzZDE4MmEtMGQyMC00MTQyLWJiMTQtOWQ4OWEyNjUwNjIzIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCIsInBob25lX251bWJlciI6IjA3NjgwMzA0NzgiLCJlbWFpbCI6ImZlbGl4b2tvdGgwNzhAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjkxMC0zMDEwMCwgVWFzaW4gR2lzaHUiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAudzZuYThmR0luZ0RQa0NiX0d6RWxid0FBQUEmdz0yOTAmaD0yMTUmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiR1bDNyUnhsSEFBZC42aXJwMkxGN2xPU3lSVjIwNEYzL2pRckc5Mzc0bGJLWFIzZXcxYzlzQyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJhZG1pbiIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MjExMzU5NjEsImV4cCI6MTcyMTE0MzE2MX0.061nVkdwZQgXI3fpZr5ftXKejkz6G02xPRoDyAlNJck

{
  "fullname": "Felix Okoth Owuor",
  "phone_number": "0768030478",
  "email": "felixokoth078@gmail.com",
  "country": "Kenya",
  "address": "910-30100, Uasin Gishu",
  "profile_image": "https://th.bing.com/th?id=OIP.w6na8fGIngDPkCb_GzElbwAAAA&w=290&h=215&c=8&rs=1&qlt=90&o=6&pid=3.1&rm=2",
  "role": "admin"
}

### Get all Users
GET http://localhost:6000/users/get-all
Content-Type: application/json

### Get get single user by Id
GET http://localhost:6000/users/get-single-user
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzlhMDdkMmItOGU4MS00MGJmLWJmZTMtN2JmYWQ3YmM5NzBiIiwiZnVsbG5hbWUiOiJCb2IgQmVsY2hlciIsInBob25lX251bWJlciI6IjA3MTIzNDU2NzgiLCJlbWFpbCI6ImJvYmJlbGNoZXIwMDFAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjQ1Ni0wMDEsIE5haXJvYmkiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAuMGFkaXRwQms1NG8wZGlEa3JSMXlpUUhhSmEmdz0yMjEmaD0yODEmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiRQZXVvLlZ5b2p4WHJQdkZkTG5USWF1WERwaHc5ZWVaM3lGVDdib0xwWHdDMkNoUXNXUXpJcSIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJtYW5hZ2VyIiwiaXNNYW5hZ2VyIjp0cnVlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpc1dlbGNvbWVkIjpmYWxzZSwiaWF0IjoxNzIxMTU0MTI3LCJleHAiOjE3MjExNjEzMjd9.lh1xu2tR4YukaDaoxuClaNYp0Oply2gwxNCAta_DTg8

### Get get user by role
GET http://localhost:6000/users/get-user-by-role
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzkzZDE4MmEtMGQyMC00MTQyLWJiMTQtOWQ4OWEyNjUwNjIzIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCIsInBob25lX251bWJlciI6IjA3NjgwMzA0NzgiLCJlbWFpbCI6ImZlbGl4b2tvdGgwNzhAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjkxMC0zMDEwMCwgVWFzaW4gR2lzaHUiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAudzZuYThmR0luZ0RQa0NiX0d6RWxid0FBQUEmdz0yOTAmaD0yMTUmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiR1bDNyUnhsSEFBZC42aXJwMkxGN2xPU3lSVjIwNEYzL2pRckc5Mzc0bGJLWFIzZXcxYzlzQyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJhZG1pbiIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MjExMzU5NjEsImV4cCI6MTcyMTE0MzE2MX0.061nVkdwZQgXI3fpZr5ftXKejkz6G02xPRoDyAlNJck

### Get get users by date created
GET http://localhost:6000/users/get-all-by-date-created
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzkzZDE4MmEtMGQyMC00MTQyLWJiMTQtOWQ4OWEyNjUwNjIzIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCIsInBob25lX251bWJlciI6IjA3NjgwMzA0NzgiLCJlbWFpbCI6ImZlbGl4b2tvdGgwNzhAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjkxMC0zMDEwMCwgVWFzaW4gR2lzaHUiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAudzZuYThmR0luZ0RQa0NiX0d6RWxid0FBQUEmdz0yOTAmaD0yMTUmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiR1bDNyUnhsSEFBZC42aXJwMkxGN2xPU3lSVjIwNEYzL2pRckc5Mzc0bGJLWFIzZXcxYzlzQyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJhZG1pbiIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MjExMzU5NjEsImV4cCI6MTcyMTE0MzE2MX0.061nVkdwZQgXI3fpZr5ftXKejkz6G02xPRoDyAlNJck

### Update user role by admin
PUT http://localhost:6000/users/update-role-by-admin/79a07d2b-8e81-40bf-bfe3-7bfad7bc970b
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzkzZDE4MmEtMGQyMC00MTQyLWJiMTQtOWQ4OWEyNjUwNjIzIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCBPd3VvciIsInBob25lX251bWJlciI6IjA3NjgwMzA0NzgiLCJlbWFpbCI6ImZlbGl4b2tvdGgwNzhAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjkxMC0zMDEwMCwgVWFzaW4gR2lzaHUiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAudzZuYThmR0luZ0RQa0NiX0d6RWxid0FBQUEmdz0yOTAmaD0yMTUmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiR1bDNyUnhsSEFBZC42aXJwMkxGN2xPU3lSVjIwNEYzL2pRckc5Mzc0bGJLWFIzZXcxYzlzQyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJhZG1pbiIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MjExNTA1NzYsImV4cCI6MTcyMTE1Nzc3Nn0.UEylHfP0TWjmesgedXjZEKGGpkn0Z3oPZZBCtxRdjek

### Update all users role by admin
PUT http://localhost:6000/users/update-all-user-roles
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzkzZDE4MmEtMGQyMC00MTQyLWJiMTQtOWQ4OWEyNjUwNjIzIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCBPd3VvciIsInBob25lX251bWJlciI6IjA3NjgwMzA0NzgiLCJlbWFpbCI6ImZlbGl4b2tvdGgwNzhAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjkxMC0zMDEwMCwgVWFzaW4gR2lzaHUiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAudzZuYThmR0luZ0RQa0NiX0d6RWxid0FBQUEmdz0yOTAmaD0yMTUmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiR1bDNyUnhsSEFBZC42aXJwMkxGN2xPU3lSVjIwNEYzL2pRckc5Mzc0bGJLWFIzZXcxYzlzQyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJhZG1pbiIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MjExNTA1NzYsImV4cCI6MTcyMTE1Nzc3Nn0.UEylHfP0TWjmesgedXjZEKGGpkn0Z3oPZZBCtxRdjek

### Soft delete user by admin
PUT http://localhost:6000/users/soft-delete-user/79a07d2b-8e81-40bf-bfe3-7bfad7bc970b
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzkzZDE4MmEtMGQyMC00MTQyLWJiMTQtOWQ4OWEyNjUwNjIzIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCBPd3VvciIsInBob25lX251bWJlciI6IjA3NjgwMzA0NzgiLCJlbWFpbCI6ImZlbGl4b2tvdGgwNzhAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjkxMC0zMDEwMCwgVWFzaW4gR2lzaHUiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAudzZuYThmR0luZ0RQa0NiX0d6RWxid0FBQUEmdz0yOTAmaD0yMTUmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiR1bDNyUnhsSEFBZC42aXJwMkxGN2xPU3lSVjIwNEYzL2pRckc5Mzc0bGJLWFIzZXcxYzlzQyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJhZG1pbiIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MjExNTA1NzYsImV4cCI6MTcyMTE1Nzc3Nn0.UEylHfP0TWjmesgedXjZEKGGpkn0Z3oPZZBCtxRdjek

### Retrieve deleted user by admin
PUT http://localhost:6000/users/retrieve-deleted-user/79a07d2b-8e81-40bf-bfe3-7bfad7bc970b
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzkzZDE4MmEtMGQyMC00MTQyLWJiMTQtOWQ4OWEyNjUwNjIzIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCBPd3VvciIsInBob25lX251bWJlciI6IjA3NjgwMzA0NzgiLCJlbWFpbCI6ImZlbGl4b2tvdGgwNzhAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjkxMC0zMDEwMCwgVWFzaW4gR2lzaHUiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAudzZuYThmR0luZ0RQa0NiX0d6RWxid0FBQUEmdz0yOTAmaD0yMTUmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiR1bDNyUnhsSEFBZC42aXJwMkxGN2xPU3lSVjIwNEYzL2pRckc5Mzc0bGJLWFIzZXcxYzlzQyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJhZG1pbiIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MjExNTA1NzYsImV4cCI6MTcyMTE1Nzc3Nn0.UEylHfP0TWjmesgedXjZEKGGpkn0Z3oPZZBCtxRdjek

### Retrieve all deleted users by admin
PUT http://localhost:6000/users/retrieve-deleted-users
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzkzZDE4MmEtMGQyMC00MTQyLWJiMTQtOWQ4OWEyNjUwNjIzIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCBPd3VvciIsInBob25lX251bWJlciI6IjA3NjgwMzA0NzgiLCJlbWFpbCI6ImZlbGl4b2tvdGgwNzhAZ21haWwuY29tIiwiY291bnRyeSI6IktlbnlhIiwiYWRkcmVzcyI6IjkxMC0zMDEwMCwgVWFzaW4gR2lzaHUiLCJwcm9maWxlX2ltYWdlIjoiaHR0cHM6Ly90aC5iaW5nLmNvbS90aD9pZD1PSVAudzZuYThmR0luZ0RQa0NiX0d6RWxid0FBQUEmdz0yOTAmaD0yMTUmYz04JnJzPTEmcWx0PTkwJm89NiZwaWQ9My4xJnJtPTIiLCJwYXNzd29yZCI6IiQyYiQxMiR1bDNyUnhsSEFBZC42aXJwMkxGN2xPU3lSVjIwNEYzL2pRckc5Mzc0bGJLWFIzZXcxYzlzQyIsImNyZWF0ZWRBdCI6IjIwMjQtMDctMTZUMDA6MDA6MDAuMDAwWiIsInJvbGUiOiJhZG1pbiIsImlzTWFuYWdlciI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MjExNTA1NzYsImV4cCI6MTcyMTE1Nzc3Nn0.UEylHfP0TWjmesgedXjZEKGGpkn0Z3oPZZBCtxRdjek
