import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class DummyService {
  users: User[] = [
  {
    user_id: '1',
    full_name: 'John Doe',
    phone_number: '123-456-7890',
    email: 'johndoe@example.com',
    country: 'USA',
    profile_image: "profile.png",
    address: '123 Main St, Anytown, USA',
    isManager: false,
    date_created: new Date('2023-01-15'),
    role: 'user',
    activity: 'attendee',
    booked_events_id: ['event1', 'event2'],
  },
  {
    user_id: '2',
    full_name: 'Jane Smith',
    phone_number: '234-567-8901',
    email: 'janesmith@example.com',
    country: 'Canada',
    profile_image: "profile.png",
    address: '456 Maple Rd, Anytown, Canada',
    isManager: false,
    date_created: new Date('2023-02-20'),
    role: 'user',
    activity: 'attendee',
    booked_events_id: ['event3'],
  },
  {
    user_id: '3',
    full_name: 'Mike Johnson',
    phone_number: '345-678-9012',
    email: 'mikejohnson@example.com',
    country: 'UK',
    profile_image: "profile.png",
    address: '789 Oak St, Anytown, UK',
    isManager: false,
    date_created: new Date('2023-03-25'),
    role: 'user',
    activity: 'attendee',
    booked_events_id: ['event2', 'event4'],
  },
  {
    user_id: '4',
    full_name: 'Emily Brown',
    phone_number: '456-789-0123',
    email: 'emilybrown@example.com',
    country: 'Australia',
    profile_image: "profile.png",
    address: '123 Pine St, Anytown, Australia',
    isManager: false,
    date_created: new Date('2023-04-30'),
    role: 'user',
    activity: 'attendee',
    booked_events_id: ['event5'],
  },
  {
    user_id: '5',
    full_name: 'David Wilson',
    phone_number: '567-890-1234',
    email: 'davidwilson@example.com',
    country: 'Germany',
    profile_image: "profile.png",
    address: '456 Birch Rd, Anytown, Germany',
    isManager: false,
    date_created: new Date('2023-05-05'),
    role: 'user',
    activity: 'attendee',
    booked_events_id: ['event1', 'event6'],
  },
  {
    user_id: '6',
    full_name: 'Sarah Davis',
    phone_number: '678-901-2345',
    email: 'sarahdavis@example.com',
    country: 'France',
    profile_image: "profile.png",
    address: '789 Cedar St, Anytown, France',
    isManager: false,
    date_created: new Date('2023-06-10'),
    role: 'user',
    activity: 'attendee',
    booked_events_id: ['event3', 'event4', 'event7'],
  },
  ];

  events: Events[] = [
  {
    user_id: "1",
    event_id: "event1",
    event_name: "Tech Conference 2024",
    short_description: "A conference for tech enthusiasts",
    long_description: "A detailed event for singles, groups, and couples interested in the latest tech innovations.",
    location: "San Francisco, USA",
    start_date: new Date("2024-08-01"),
    end_date: new Date("2024-08-05"),
    images: ["img1.jpg", "img2.jpg"],
    booking_price: 300,
    booking_deadline_date: new Date("2024-07-20"),
    category: "Conference",
    ticket_type: "singles",
    no_of_tickets_available: 100,
    price_per_group: 0,
    event_status: "pending",
    isApproved: false
  },
  {
      user_id: "2",
      event_id: "event2",
      event_name: "Music Festival",
      short_description: "An outdoor music festival",
      long_description: "A fun-filled music event for singles and groups, featuring various artists.",
      location: "Toronto, Canada",
      start_date: new Date("2024-09-10"),
      end_date: new Date("2024-09-12"),
      images: ["img3.jpg", "img4.jpg"],
      booking_price: 150,
      booking_deadline_date: new Date("2024-08-30"),
      category: "Festival",
      ticket_type: "group",
      no_of_tickets_available: 200,
      price_per_group: 500,
      event_status: "pending",
      isApproved: false
  },
  {
      user_id: "3",
      event_id: "event3",
      event_name: "Art Exhibition",
      short_description: "An exhibition of modern art",
      long_description: "An exclusive event for singles and couples to appreciate modern art.",
      location: "London, UK",
      start_date: new Date("2024-10-01"),
      end_date: new Date("2024-10-03"),
      images: ["img5.jpg", "img6.jpg"],
      booking_price: 50,
      booking_deadline_date: new Date("2024-09-20"),
      category: "Exhibition",
      ticket_type: "singles",
      no_of_tickets_available: 150,
      price_per_group: 0,
      event_status: "pending",
      isApproved: false
  },
  {
      user_id: "4",
      event_id: "event4",
      event_name: "Cooking Workshop",
      short_description: "A workshop for cooking enthusiasts",
      long_description: "A hands-on workshop for couples and singles to learn new cooking techniques.",
      location: "Sydney, Australia",
      start_date: new Date("2024-11-15"),
      end_date: new Date("2024-11-17"),
      images: ["img7.jpg", "img8.jpg"],
      booking_price: 200,
      booking_deadline_date: new Date("2024-11-01"),
      category: "Workshop",
      ticket_type: "couples",
      no_of_tickets_available: 50,
      price_per_group: 0,
      event_status: "pending",
      isApproved: false
  },
  {
      user_id: "5",
      event_id: "event5",
      event_name: "Yoga Retreat",
      short_description: "A relaxing yoga retreat",
      long_description: "A serene retreat for singles, groups, and couples to practice yoga and meditation.",
      location: "Berlin, Germany",
      start_date: new Date("2024-12-05"),
      end_date: new Date("2024-12-10"),
      images: ["img9.jpg", "img10.jpg"],
      booking_price: 400,
      booking_deadline_date: new Date("2024-11-25"),
      category: "Retreat",
      ticket_type: "singles",
      no_of_tickets_available: 30,
      price_per_group: 0,
      event_status: "pending",
      isApproved: false
  },
  {
      user_id: "6",
      event_id: "event6",
      event_name: "Business Summit",
      short_description: "A summit for business professionals",
      long_description: "An event for singles, groups, and couples to network and learn about business trends.",
      location: "Paris, France",
      start_date: new Date("2024-07-20"),
      end_date: new Date("2024-07-22"),
      images: ["img11.jpg", "img12.jpg"],
      booking_price: 250,
      booking_deadline_date: new Date("2024-07-10"),
      category: "Summit",
      ticket_type: "singles",
      no_of_tickets_available: 75,
      price_per_group: 0,
      event_status: "pending",
      isApproved: false
  }
  ]

bookings: Booking[] = [
  {
    booking_id: "booking1",
    user_id: "1",
    event_id: "event1",
    images: ["img1.jpg", "img2.jpg"],
    event_name: "Tech Conference 2024",
    ticket_type: "singles",
    book_status: "pending",
    isCanceled: false,
    dateCreated: new Date("2024-07-01"),
    price_paid: 300
  },
  {
    booking_id: "booking2",
    user_id: "2",
    event_id: "event2",
    images: ["img3.jpg", "img4.jpg"],
    event_name: "Music Festival",
    ticket_type: "group",
    book_status: "pending",
    isCanceled: false,
    dateCreated: new Date("2024-07-02"),
    price_paid: 500
  },
  {
    booking_id: "booking3",
    user_id: "3",
    event_id: "event3",
    images: ["img5.jpg", "img6.jpg"],
    event_name: "Art Exhibition",
    ticket_type: "singles",
    book_status: "pending",
    isCanceled: false,
    dateCreated: new Date("2024-07-03"),
    price_paid: 50
  },
  {
    booking_id: "booking4",
    user_id: "4",
    event_id: "event4",
    images: ["img7.jpg", "img8.jpg"],
    event_name: "Cooking Workshop",
    ticket_type: "couples",
    book_status: "pending",
    isCanceled: false,
    dateCreated: new Date("2024-07-04"),
    price_paid: 200
  },
  {
    booking_id: "booking5",
    user_id: "5",
    event_id: "event5",
    images: ["img9.jpg", "img10.jpg"],
    event_name: "Yoga Retreat",
    ticket_type: "singles",
    book_status: "pending",
    isCanceled: false,
    dateCreated: new Date("2024-07-05"),
    price_paid: 400
  },
  {
    booking_id: "booking6",
    user_id: "6",
    event_id: "event6",
    images: ["img11.jpg", "img12.jpg"],
    event_name: "Business Summit",
    ticket_type: "singles",
    book_status: "pending",
    isCanceled: false,
    dateCreated: new Date("2024-07-06"),
    price_paid: 250
  }
];
  constructor() {}
}
